P=phantom('Modified Shepp-Logan',512);
theta=linspace(0,360,360);
dtheta=theta(2)-theta(1);
D=500;
r_spacing=0.05;
[F1,F1Angle,F1Theta]=fanbeam(P,D,'FanSensorSpacing',r_spacing,'FanSensorGeometry','arc','FanRotationIncrement',dtheta);
% F2=ifanbeam(F1,D,'FanSensorSpacing',0.1,'FanSensorGeometry','arc','FanRotationIncrement',dtheta);
% [R,xp]=radon(P,theta);
% imshow(R,[]);
% f=fopen('D:\workspace\Reconstruction\src\parallel.dat','w');
% fwrite(f,R,'float32');
% fclose(f);